name = "cf-worker-ws-dev" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"

[vars]
# UUID = "95e491ad-81da-42f5-8626-5ba34e0009e5"
# PROXYIP = "edgetunnel.anycast.eu.org"
# DNS_RESOLVER_URL = "https://sky.rethinkdns.com/1:-Pf_v___9_8A_AMAIgE8kMABVDDmKOHTAKg="
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "f0ae0913-6fdb-4165-aa33-9cd21cef63c2,1c041be4-9b17-46c6-b451-f2e750aa7205,95e491ad-81da-42f5-8626-5ba34e0009e5"
